version: '3'

services:
  jupyterlab:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=token
    command: "start-notebook.sh \
      --NotebookApp.iopub_data_rate_limit=1.0e10"
